version: 0.0
os: linux
files:
 - source: /index.html
   destination: /var/www/html/multi
hooks:
  BeforeInstall:
    - location: BeforeInstall.sh
      timeout: 300
      runas: root
      when: manual